import sys
import os
import argparse

# Add the 'src' directory to the Python path to find the builder
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from src.bog_builder_new import BogFolderBuilder


def main():
    """
    This script builds a minimal test case to isolate and debug the behavior
    of the NumericSwitch component when generated by the BogFolderBuilder.
    """
    parser = argparse.ArgumentParser(
        description="Build a .bog file to test the NumericSwitch component."
    )
    parser.add_argument(
        "-o", "--output_dir", default="examples", help="Output directory for the .bog file."
    )
    args = parser.parse_args()

    script_filename = os.path.basename(__file__).replace(".py", "")

    builder = BogFolderBuilder("NumericSwitch_Isolation_Test")
    print("Creating top-level components for the test...")

    # --- Inputs ---
    builder.add_boolean_writable("Switch_Control", default_value=True)
    
    # --- Output ---
    builder.add_numeric_writable("Final_Output")

    print("Creating logic components inside 'CalculationLogic' folder...")
    builder.start_sub_folder("CalculationLogic")

    # --- Logic Blocks ---
    builder.add_component("kitControl:NumericConst", "Const_1", properties={"out": 1.0})
    builder.add_numeric_switch("Test_NumericSwitch")

    builder.end_sub_folder()

    print("Wiring components...")
    builder.add_link("Switch_Control", "out", "Test_NumericSwitch", "inSwitch")
    builder.add_link("Const_1", "out", "Test_NumericSwitch", "inTrue")
    builder.add_link("Test_NumericSwitch", "out", "Final_Output", "in16")

    bog_filename = f"{script_filename}.bog"
    output_path = os.path.join(args.output_dir, bog_filename)
    os.makedirs(args.output_dir, exist_ok=True)
    builder.save(output_path)
    print(f"\nSuccessfully created Niagara .bog file at: {output_path}")
    print("You can now test this file in Niagara Workbench to isolate the issue.")


if __name__ == "__main__":
    main()
