"""
central_plant_bog_builder.py
--------------------------------

This module exposes a convenience function for constructing a Niagara
Baja Object Graph (``.bog``) that implements a simple boiler and
chiller plant sequence.  The control logic generated by this script
illustrates how to combine comparison blocks, logical gates and
latching behaviour to implement outdoor‐air temperature based heating
and cooling with hysteresis and a free cooling deadband.

The resulting graph contains numeric setpoints for the following:

* ``OAT`` – the current outside air temperature.
* ``HeatStartSP`` – the outdoor air temperature at or below which the
  heating plant will be enabled.
* ``HeatStopSP`` – the outdoor air temperature at or above which the
  heating plant will be disabled.  Choosing a value higher than
  ``HeatStartSP`` creates hysteresis.
* ``CoolStartSP`` – the outdoor air temperature at or above which the
  cooling plant will be enabled.
* ``CoolStopSP`` – the outdoor air temperature at or below which the
  cooling plant will be disabled.  Choosing a value lower than
  ``CoolStartSP`` creates hysteresis.
* ``FreeCoolLow`` and ``FreeCoolHigh`` – the inclusive bounds of a
  “economizer” or free cooling range.  When the outdoor air
  temperature lies within this band, neither the boiler nor the
  chiller are commanded.

Two latches implement the hysteretic enable/disable behaviour.  Each
latch is set when its corresponding start condition becomes true and
reset when its stop condition becomes true.  This means the heating
plant remains on until the outdoor air has warmed past the stop
setpoint or moves into the free cooling band, even if the start
setpoint is crossed in the opposite direction.  Likewise, the cooling
plant remains on until the outdoor air has cooled past its stop
setpoint or enters the free cooling band.

Four boolean outputs are provided to drive downstream equipment:

* ``Boiler_Cmd`` – enable signal for the boiler.
* ``HeatingPump_Cmd`` – enable signal for the heating pump feeding AHU
  hot water coils.
* ``Chiller_Cmd`` – enable signal for the chiller.
* ``CoolingPump_Cmd`` – enable signal for the cooling pump feeding AHU
  chilled water coils.

To generate a ``.bog`` file using this module, call
``create_central_plant_bog`` specifying the desired output path.  See
the module’s ``__main__`` block for a CLI example.
"""

from __future__ import annotations

import argparse
import os
from typing import Optional

from bog_builder import BogFolderBuilder


def build_central_plant(builder: BogFolderBuilder) -> None:
    """Populate a :class:`BogFolderBuilder` with central plant logic.

    Parameters
    ----------
    builder : BogFolderBuilder
        The builder into which all components, inputs, outputs and links
        will be added.  The caller should instantiate the builder with a
        suitable top–level folder name before invoking this function.

    Notes
    -----
    This function does not call :meth:`BogFolderBuilder.save`; the
    caller is responsible for saving the completed graph to disk once
    populated.
    """
    # ------------------------------------------------------------------
    # Inputs and adjustable setpoints
    # ------------------------------------------------------------------
    # Outside air temperature sensed value
    builder.add_numeric_writable("OAT", default_value=55.0)
    # Heating start and stop setpoints; choose defaults to illustrate
    # hysteresis (start below stop).  Users can adjust these at run time.
    builder.add_numeric_writable("HeatStartSP", default_value=45.0)
    builder.add_numeric_writable("HeatStopSP", default_value=50.0)
    # Cooling start and stop setpoints (start above stop)
    builder.add_numeric_writable("CoolStartSP", default_value=75.0)
    builder.add_numeric_writable("CoolStopSP", default_value=70.0)
    # Free cooling deadband bounds
    builder.add_numeric_writable("FreeCoolLow", default_value=50.0)
    builder.add_numeric_writable("FreeCoolHigh", default_value=60.0)

    # ------------------------------------------------------------------
    # Outputs to drive the plant equipment
    # ------------------------------------------------------------------
    builder.add_boolean_writable("Boiler_Cmd")
    builder.add_boolean_writable("HeatingPump_Cmd")
    builder.add_boolean_writable("Chiller_Cmd")
    builder.add_boolean_writable("CoolingPump_Cmd")

    # ------------------------------------------------------------------
    # Comparison blocks for start and stop conditions
    # ------------------------------------------------------------------
    # Heating start: OAT ≤ HeatStartSP
    builder.add_component("kitControl:LessThanEqual", "Cold_Start_Compare")
    # Cooling start: OAT ≥ CoolStartSP
    builder.add_component("kitControl:GreaterThanEqual", "Hot_Start_Compare")
    # Heating stop: OAT ≥ HeatStopSP
    builder.add_component("kitControl:GreaterThanEqual", "Warm_StopHeat_Compare")
    # Cooling stop: OAT ≤ CoolStopSP
    builder.add_component("kitControl:LessThanEqual", "Cool_Stop_Compare")
    # Free cooling boundaries: OAT ≥ FreeCoolLow and OAT ≤ FreeCoolHigh
    builder.add_component("kitControl:GreaterThanEqual", "FreeCool_GE")
    builder.add_component("kitControl:LessThanEqual", "FreeCool_LE")

    # ------------------------------------------------------------------
    # Logical operators
    # ------------------------------------------------------------------
    builder.add_component("kitControl:And", "FreeCoolingMode")  # detects OAT in deadband
    builder.add_component("kitControl:Not", "Not_FreeCooling")  # invert deadband signal
    # Start gates combine start condition with Not_FreeCooling
    builder.add_component("kitControl:And", "Start_Heat_Gate")
    builder.add_component("kitControl:And", "Start_Cool_Gate")
    # Stop gates combine stop condition with FreeCoolingMode (OR)
    builder.add_component("kitControl:Or", "Stop_Heat_Or")
    builder.add_component("kitControl:Or", "Stop_Cool_Or")

    # Latches to implement hysteresis
    builder.add_component("kitControl:BooleanLatch", "Heat_Latch")
    builder.add_component("kitControl:BooleanLatch", "Cool_Latch")

    # ------------------------------------------------------------------
    # Linking: establish data flow between points and logic blocks
    # ------------------------------------------------------------------
    # Free cooling detection (OAT within [FreeCoolLow, FreeCoolHigh])
    builder.add_link("OAT", "out", "FreeCool_GE", "inA")
    builder.add_link("FreeCoolLow", "out", "FreeCool_GE", "inB")
    builder.add_link("OAT", "out", "FreeCool_LE", "inA")
    builder.add_link("FreeCoolHigh", "out", "FreeCool_LE", "inB")
    builder.add_link("FreeCool_GE", "out", "FreeCoolingMode", "inA")
    builder.add_link("FreeCool_LE", "out", "FreeCoolingMode", "inB")

    # Invert the free cooling mode; used to gate start conditions
    builder.add_link("FreeCoolingMode", "out", "Not_FreeCooling", "in")

    # Heating start: OAT ≤ HeatStartSP AND not in free cooling
    builder.add_link("OAT", "out", "Cold_Start_Compare", "inA")
    builder.add_link("HeatStartSP", "out", "Cold_Start_Compare", "inB")
    builder.add_link("Cold_Start_Compare", "out", "Start_Heat_Gate", "inA")
    builder.add_link("Not_FreeCooling", "out", "Start_Heat_Gate", "inB")

    # Cooling start: OAT ≥ CoolStartSP AND not in free cooling
    builder.add_link("OAT", "out", "Hot_Start_Compare", "inA")
    builder.add_link("CoolStartSP", "out", "Hot_Start_Compare", "inB")
    builder.add_link("Hot_Start_Compare", "out", "Start_Cool_Gate", "inA")
    builder.add_link("Not_FreeCooling", "out", "Start_Cool_Gate", "inB")

    # Heating stop: OAT ≥ HeatStopSP OR in free cooling
    builder.add_link("OAT", "out", "Warm_StopHeat_Compare", "inA")
    builder.add_link("HeatStopSP", "out", "Warm_StopHeat_Compare", "inB")
    builder.add_link("Warm_StopHeat_Compare", "out", "Stop_Heat_Or", "inA")
    builder.add_link("FreeCoolingMode", "out", "Stop_Heat_Or", "inB")

    # Cooling stop: OAT ≤ CoolStopSP OR in free cooling
    builder.add_link("OAT", "out", "Cool_Stop_Compare", "inA")
    builder.add_link("CoolStopSP", "out", "Cool_Stop_Compare", "inB")
    builder.add_link("Cool_Stop_Compare", "out", "Stop_Cool_Or", "inA")
    builder.add_link("FreeCoolingMode", "out", "Stop_Cool_Or", "inB")

    # Latch wiring: set on start and reset on stop
    builder.add_link("Start_Heat_Gate", "out", "Heat_Latch", "set")
    builder.add_link("Stop_Heat_Or", "out", "Heat_Latch", "reset")
    builder.add_link("Start_Cool_Gate", "out", "Cool_Latch", "set")
    builder.add_link("Stop_Cool_Or", "out", "Cool_Latch", "reset")

    # Connect latch outputs to final commands
    builder.add_link("Heat_Latch", "out", "Boiler_Cmd", "in16")
    builder.add_link("Heat_Latch", "out", "HeatingPump_Cmd", "in16")
    builder.add_link("Cool_Latch", "out", "Chiller_Cmd", "in16")
    builder.add_link("Cool_Latch", "out", "CoolingPump_Cmd", "in16")


def create_central_plant_bog(output_path: str) -> str:
    """Create and save the central plant .bog file.

    Parameters
    ----------
    output_path : str
        Full file system path (including filename) where the resulting
        ``.bog`` archive should be written.  The parent directory will
        be created if it does not already exist.

    Returns
    -------
    str
        The absolute path to the saved ``.bog`` file.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    builder = BogFolderBuilder("CentralPlantControl", debug=False)
    build_central_plant(builder)
    builder.save(output_path)
    return os.path.abspath(output_path)


def main(args: Optional[list[str]] = None) -> None:
    """Command–line entry point for generating a central plant bog file.

    Usage examples::

        python central_plant_bog_builder.py -o output/central.bog

    The ``-o``/``--output`` argument specifies where the ``.bog`` file
    should be written.  If omitted, the file will be created in the
    current directory as ``central_plant.bog``.
    """
    parser = argparse.ArgumentParser(description="Generate a central plant .bog file with heating, cooling and free cooling logic.")
    parser.add_argument("-o", "--output", default="central_plant.bog", help="Destination .bog file path")
    parsed_args = parser.parse_args(args)
    out_path = parsed_args.output
    result_path = create_central_plant_bog(out_path)
    print(f"Successfully created central plant .bog at: {result_path}")


if __name__ == "__main__":
    main()