"""

kitControl:LeadLagCycles 2-Pump Rotator (AI-Generated)
-------------------------------------------------------

This script, generated by an AI assistant based on user requirements,
creates a robust demonstration for a 2-pump lead-lag rotator using the
kitControl:LeadLagCycles component.

All core calculation logic is organized into a 'Logic' sub-folder to
keep the top-level view clean and focused on the main inputs and outputs.

Use in Central Plant staging for chillers, boilers, pumps, etc.
The 'maxRuntime' property is set to "8h" but can be configured for any
desired rotation interval, such as weekly.

Algorithm:
- A self-enabling signal is created by combining both 'Pump_Status'
    points through an 'Or' block. This signal is fed into the 'in' slot
    of the LeadLagCycles block, calling for one pump to run.
- The block is configured for two outputs ('numberOutputs' = 2).
- The outputs of the block command two individual pumps (represented by
    BooleanWritables at the top level).
- Each pump command is also wired to the 'countUp' slot of a dedicated
    'kitControl:Counter' block to track start/stop cycles.
- The output of each counter is wired back into the corresponding 'cycleCount'
    slot on the LeadLagCycles block. This is the primary rotation method.
- The combined status signal is also wired to the 'feedback' slot for
    failure detection.
- A secondary rotation occurs if a pump exceeds the 'maxRuntime'.
- Configurable timers for 'feedbackDelay' and 'clearAlarmTime'
    are included as component properties for robust operation.


How it Works:
The logic creates a self-enabling loop. If either of the two pump status
points is 'true', the 'in' slot of the rotator block is enabled, calling
for one pump to run.

Rotation Logic:
Every time the block needs to start a pump, it looks at the
cycleCount input for both pumps and always chooses the one with the lower number.

This is its primary method for keeping the wear on the pumps
as even as possible over time. The maxRuntime setting is just
a backup to force a rotation if one pump happens to run for
10 hours straight without ever shutting off.
"""

import sys
import os
import argparse

# The script must append the path to the bog_builder library.
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "src")))
from bog_builder import BogFolderBuilder


def main():

    # Per instructions, accept an output directory via command-line argument.
    parser = argparse.ArgumentParser(
        description="Build a .bog file for a 2-pump lead-lag rotator with status-driven input."
    )
    parser.add_argument(
        "-o",
        "--output_dir",
        default="examples",
        help="Output directory for the .bog file.",
    )
    args = parser.parse_args()

    builder = BogFolderBuilder("Two_Pump_Lead_Lag_Rotator_Status_Input", debug=True)
    NUM_PUMPS = 2

    # --- Top-Level I/O Components ---
    # Create command and status writable points for each of the 2 pumps.
    pump_names = [f"Pump_{i+1}" for i in range(NUM_PUMPS)]
    for name in pump_names:
        builder.add_boolean_writable(f"{name}_Cmd", default_value=False)
        # The status writable simulates feedback from the pump's motor starter.
        builder.add_boolean_writable(f"{name}_Status", default_value=False)

    builder.add_boolean_writable(f"Chiller_sys_Enable", default_value=False)

    # The core LeadLagCycles block, configured for 2 outputs.
    # Time values must be specified as a string of milliseconds or a time format like "10s".
    lead_lag_properties = {
        "numberOutputs": NUM_PUMPS,
        "feedbackDelay": "30",
        "clearAlarmTime": "1m",
    }
    builder.add_component(
        "kitControl:LeadLagCycles", "Pump_Rotator_Block", properties=lead_lag_properties
    )

    # A counter for each pump to track start/stop cycles for rotation logic.
    for name in pump_names:
        builder.add_component("kitControl:Counter", f"{name}_CycleCounter")

    # An OR gate combines the 2 status signals into a single signal.
    builder.add_component("kitControl:Or", "Feedback_Or")

    # --- Component Wiring ---

    # --- Wire the status and feedback logic ---
    # The OR gate combines the status signals from both pumps.
    builder.add_link("Pump_1_Status", "out", "Feedback_Or", "inA")
    builder.add_link("Pump_2_Status", "out", "Feedback_Or", "inB")

    # The combined status from the OR gate now drives the main 'in' slot.
    # A boolean 'true' will be interpreted as a numeric '1.0', calling for one pump.
    builder.add_link("Chiller_sys_Enable", "out", "Pump_Rotator_Block", "in")

    # The combined status is ALSO wired to the feedback slot for failure detection.
    builder.add_link("Feedback_Or", "out", "Pump_Rotator_Block", "feedback")

    # Loop through each pump to wire its command and cycle counter.
    for i in range(NUM_PUMPS):
        pump_name = pump_names[i]

        # Generate alphabetic slot names ('outA', 'outB') for the rotator block.
        output_slot = f"out{chr(ord('A') + i)}"
        cycle_count_slot = f"cycleCount{chr(ord('A') + i)}"

        # 1. Link the rotator's output to the final pump command writable.
        builder.add_link("Pump_Rotator_Block", output_slot, f"{pump_name}_Cmd", "in16")

        # 2. When a pump is commanded on, trigger its cycle counter to increment.
        builder.add_link(
            f"{pump_name}_Cmd", "out", f"{pump_name}_CycleCounter", "countUp"
        )

        # 3. Link the accumulated cycle count back to the rotator block.
        builder.add_link(
            f"{pump_name}_CycleCounter", "out", "Pump_Rotator_Block", cycle_count_slot
        )

    # --- Save the .bog file ---
    # The final .bog filename is hardcoded within the script.
    bog_filename = "two_pump_rotator_status_driven.bog"
    output_path = os.path.join(args.output_dir, bog_filename)
    os.makedirs(args.output_dir, exist_ok=True)
    builder.save(output_path)
    print(f"Successfully created Niagara .bog file at: {os.path.abspath(output_path)}")


if __name__ == "__main__":
    main()
